# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- '*'

pr:
- '*'

 

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'
  DotNetCoreVersion: '2.2.203'


steps:
  - task: DotNetCoreInstaller@0
    displayName: Install .NET Core $(DotNetCoreVersion)
    inputs:
      version: $(DotNetCoreVersion)
  - script: dotnet restore ./src/GraphQL-AspNetCore-2.2.sln
    displayName: dotnet restore
    

  - script: dotnet build --configuration $(buildConfiguration) ./src/GraphQL-AspNetCore-2.2.sln
    displayName: 'dotnet build $(buildConfiguration)'
  
  # do this after other tasks such as building
  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: '**/*Tests/*.csproj'
      arguments: '--configuration $(buildConfiguration) --logger trx --collect "Code coverage"'
    
 

  - task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
